services:
  ebook2audiobook:
    #image: docker.io/athomasson2/ebook2audiobook:latest  # <-- Use prebuilt image instead of building
    image: ebook2audiobook:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebook2audiobook
    working_dir: /app
    # To update ebook2audiobook to the latest you may have to rebuild  
    entrypoint: ["python", "app.py", "--script_mode", "full_docker"]
    command: [] # <- Extra ebook2audiobook parameters can be added here
    # The dir containing this docker-compose.yml file will be used as the base directory for any commands.
    # Example Headless || command: ["--headless", "--ebook", "The-Tell-Tale-Heart.epub", "--tts_engine", "yourtts"] # "The-Tell-Tale-Heart.epub" file is located in the same dir as this docker-compose.yml. # More compose headless info can be found at wiki "https://github.com/DrewThomasson/ebook2audiobook/wiki/Docker-Compose-Headless-guide"
    tty: true
    stdin_open: true
    ports:
      - 7860:7860 # Maps container's port 7860 to the host's port 7860.

    # ---------------------------------------------------
    # UNIVERSAL GPU SUPPORT (NVIDIA + ROCm + Intel XPU)
    # ---------------------------------------------------

    # NVIDIA (WSL2 + Linux)
    # NOTE: Podman DOES NOT support "runtime: nvidia"
    # It only supports direct /dev/nvidia* mappings below.
    devices:
      # NVIDIA (ignored if missing)
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm

      # AMD ROCm (ignored if missing)
      - /dev/kfd:/dev/kfd

      # Intel XPU + also used by NVIDIA/AMD Mesa (ignored if missing)
      - /dev/dri:/dev/dri

    # Needed for ROCm + Intel iGPU (ignored if groups do not exist)
    group_add:
      - video
      - render

    # Additional optional NVIDIA request (ignored on non-NVIDIA)
    # NOTE: Podman ignores `deploy` entirely, but we preserve it for symmetry
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: ["gpu"]
        limits: {} # Keeps limits as an empty mapping to avoid errors. Uncomment and configure below.

    volumes:
      - ./:/app  # Maps the local directory to the container.

# Common Issues: ----
# --> `python: can't open file '/home/user/app/app.py': [Errno 2] No such file or directory`
# Removed all post arguments as CMD was replaced with ENTRYPOINT in the Dockerfile  
# Example correction:  
# Before: command: ["python", "app.py", "--script_mode", "full_docker"] or -> `docker run athomasson2/ebook2audiobook python app.py --script_mode full_docker`
# After: nothing needed  or just -> `docker run athomasson2/ebook2audiobook`
# Extra arguments after app.py can still be added to the -> command: [] 
# Example adding extra arguments -> command: ["--share"] or -> command: ["--help"]