version: "3.9"

services:
  ebook2audiobook:
    # Uncomment to use pre-built image instead of building locally
    #image: docker.io/athomasson2/ebook2audiobook:latest
    image: ${BUILD_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ebook2audiobook
    working_dir: /app
    entrypoint: ["python", "app.py", "--script_mode", "full_docker"]
    command: [] # Extra ebook2audiobook parameters can be added here
    tty: true
    stdin_open: true
    ports:
      - 7860:7860
    privileged: true
    # Needed for ROCm + Intel iGPU
    group_add:
      - video
      - render
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    security_opt:
      - label=disable
    annotation:
      io.containers.nvidia: "true"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./:/app